meta:
  res_path: res/
  generator_path: res/
generator:
  - testsuite: TestSuite1
    files:
      - file1.cpp:
        members:
          - member1:
              - std::string
              - "\"Hello World\""
        properties:
          - property1: 1