name: setup, build, test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: vcpkg
        run: |
          sh tooling/init_vcpkg.sh
      - name: build
        run: |
          sh tooling/build.sh
      - name: test
        run: |
          cd build/test/backend
          ctest --output-junit test-results.xml
      - name: upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test/backend/test-results.xml