name: setup, build, test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: run-vcpkg
          uses: lukka/run-vcpkg@v11
        - uses: lukka/get-cmake@latest 
        - name: build        
          uses: lukka/run-cmake@v10
        - name: test
          run: ctest


