name: setup, build, test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: run-vcpkg
          uses: lukka/run-vcpkg@v7.6
        - name: make
          run: make
        - name: test
          run: ctest


